import images from '~/assets/images';
const dataSliderProducts = [
    {
        id: 1,
        src: images.product1,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 2,
        src: images.product2,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 3,
        src: images.product3,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 4,
        src: images.product4,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 5,
        src: images.product5,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 6,
        src: images.product6,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 7,
        src: images.product7,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 8,
        src: images.product8,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 9,
        src: images.product9,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 10,
        src: images.product10,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 11,
        src: images.product11,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
    {
        id: 12,
        src: images.product12,
        title: 'The mirror vintage',
        rating: 4.5,
        desc: 'Get the best course, gain knowledge and shine for your future career.',
        price: 120.75,
    },
];

export default dataSliderProducts;
